version: "3.9"

services:
  api_express:
    container_name: express_node
    image: api_entrega_sp4
    build: .
    ports:
      - 3333:3333
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB=products_management
      - DB_PORT=5432
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'  
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products_management
    healthcheck:
      test: psql -U postgres products_management || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql 
      